# Generated by Django 2.1 on 2018-09-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20180909_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='picture',
        ),
    ]
