# Generated by Django 2.1 on 2018-09-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20180909_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.SmallIntegerField(default=1),
        ),
    ]
